services:
  aresindexer:
    image: edence/ohdsi-aresindexer
    environment:
      # NOTE - vars below reference a '.env' file (same dir), with the format:
      # -------------------
      # CDM_SCHEMA=omopcdm
      # RESULTS_SCHEMA=results
      # -------------------
      # DO NOT quote the values in this .env file
      CDM_VERSION: "5.3.1"
      SOURCE_NAME: "${CDM_SOURCE}"
      CDM_SCHEMA: "${CDM_SCHEMA}"
      RESULTS_SCHEMA: "${RESULTS_SCHEMA}"
      DB_DBMS: "postgresql"
      DB_HOSTNAME: "${TARGET_SERVER}"
      DB_NAME: "${TARGET_DATABASE}"
      DB_PORT: 5432
      DB_USERNAME: "${TARGET_USERNAME}"
      DB_PASSWORD: "${TARGET_PASSWORD}"
      RUN_MODE: "SOURCE" # MUST BE IN: ["SOURCE", "NETWORK"]
    volumes:
      - ./data:/output/ares/data
