name: Docker

"on":
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

jobs:
  # https://github.com/edencehealth/workflows
  docker:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@distributed-builders
    with:
      container_name: ohdsi-aresindexer
    secrets: inherit
